version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend_network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - backend_network
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
    networks:
      - db_network
    secrets:
      - db_root_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db_network:
    driver: bridge
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password
